# Generated by Django 6.0 on 2025-12-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='preferred_time',
            field=models.CharField(choices=[('morning', 'Morning (9:00–11:59 AM)'), ('afternoon', 'Afternoon (12:00–3:59 PM)'), ('evening', 'Evening (4:00–7:00 PM)'), ('flexible', "I'm flexible / No specific time")], max_length=20),
        ),
    ]
