"""
Django settings for metta_site project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-)enli+rs=_5-h=-&&q-ru4%7r&oer(-clacerj)!(td=_@8(i+",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com",
    "mettabhavanatherapy.com",
    "www.mettabhavanatherapy.com",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "metta_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "metta_site.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ==============================
# Resend Email Settings
# ==============================

# Put this in Render > Environment:
# RESEND_API_KEY = re_...
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "").strip()

# Where YOU want to receive appointment notifications
# Put this in Render > Environment too:
# CLINIC_NOTIFY_EMAIL = mettabhavana.wellness@gmail.com
CLINIC_NOTIFY_EMAIL = os.environ.get("CLINIC_NOTIFY_EMAIL", "mettabhavana.wellness@gmail.com").strip()

# Sender shown to the user. Must be verified in Resend.
# Use a verified sender like: no-reply@mettabhavanatherapy.com
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "Metta Bhavana <no-reply@mettabhavanatherapy.com>",
).strip()

# Optional: a safe fallback sender (only if you have one verified in Resend)
# Example: "Resend Sandbox <onboarding@resend.dev>"
FALLBACK_FROM_EMAIL = os.environ.get("FALLBACK_FROM_EMAIL", "").strip()

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
